/**
 * Wakey Owl — Royal Indian & Global Specialty Coffee Dataset
 * Deeply researched estate micro-lots, botanical varietals, and gourmet culinary pairings.
 */

const WAKEY_PRODUCTS = [
  {
    id: "attikan-estate-reserve",
    name: "Attikan Estate Royal Reserve",
    subtitle: "High-Elevation Biligirirangana Hills (BR Hills)",
    category: "estate-single-origin",
    badge: "1,750m Pinnacle Harvest",
    priceINR: 890.00,
    rating: 4.97,
    reviewsCount: 184,
    cuppingScore: 94.8,
    roastLevel: "Medium-Dark (Vienna Roast)",
    altitude: "1,650m – 1,750m (BR Hills, Karnataka)",
    estate: "Attikan Estate — Founded 1888",
    varietal: "SLN 79.5 & Selection 9 (100% Arabica)",
    process: "Washed & Cryogenic Nitrogen Stasis",
    image: "assets/images/obsidian_dark.jpg",
    accentColor: "#FF9E1B",
    flavorNotes: ["Spiced Mysore Jaggery", "Dark Cacao 85%", "Roasted Hazelnut", "Sun-Dried Fig"],
    description: "Nestled within the sacred, mist-veiled Biligirirangana tiger corridor at 1,750m. Attikan represents the pinnacle of Indian high-altitude shade-grown Arabica, celebrated for its dense body, subtle spice resonance, and total absence of bitterness.",
    recommendedBrew: "South Indian Filter / French Press / Espresso",
    foodPairings: ["Mysore Pak with Cardamom", "Dark Chocolate Jaggery Truffles", "Almond Croissants", "Aged Smoked Gouda"],
    caffeineIndex: "Deep Cognitive Sustained Focus",
    radar: {
      intensity: 90,
      acidity: 30,
      sweetness: 88,
      body: 95,
      aroma: 92
    },
    inStock: true,
    isImperialCuration: false
  },
  {
    id: "ratnagiri-pearl-south",
    name: "Ratnagiri 'Pearl of South'",
    subtitle: "Anaerobic Natural Micro-Lot (Chikmagalur)",
    category: "estate-single-origin",
    badge: "SCA Cupping 95.2",
    priceINR: 1150.00,
    rating: 4.99,
    reviewsCount: 226,
    cuppingScore: 95.2,
    roastLevel: "Light-Medium (City+ Roast)",
    altitude: "1,450m – 1,520m (Bababudangiri Range, Chikmagalur)",
    estate: "Ratnagiri Estate — 'Pearl Mountain'",
    varietal: "Red Catuai & Chandragiri Micro-Parcel",
    process: "72h Anaerobic Yeast Fermentation & Raised Bed Solar Drying",
    image: "assets/images/solar_geisha.jpg",
    accentColor: "#F5D061",
    flavorNotes: ["Ratnagiri Alphonso Mango", "Wild Blackberry", "Bergamot Orange", "Forest Honey"],
    description: "Cultivated under dense three-tier silver oak and wild fig canopies in the historic cradle of Indian coffee. This anaerobic lot undergoes 72 hours of temperature-controlled yeast fermentation to yield vibrant tropical aromatics reminiscent of ripe Alphonso mango and floral wild honey.",
    recommendedBrew: "Quantum Pour-Over (V60/Chemex) / AeroPress",
    foodPairings: ["Lemon Zest Madeleine", "Mango Panna Cotta", "Pistachio Baklava", "Mild Goat Cheese Toast"],
    caffeineIndex: "Electric Radiance & Flow-State",
    radar: {
      intensity: 70,
      acidity: 92,
      sweetness: 94,
      body: 72,
      aroma: 98
    },
    inStock: true,
    isImperialCuration: false
  },
  {
    id: "araku-tribal-reserve",
    name: "Araku Valley Tribal Terroir",
    subtitle: "Biodynamic Micro-Lot (Eastern Ghats)",
    category: "estate-single-origin",
    badge: "100% Biodynamic Certified",
    priceINR: 950.00,
    rating: 4.95,
    reviewsCount: 162,
    cuppingScore: 94.2,
    roastLevel: "Medium Roast (Harmonic Curve)",
    altitude: "1,200m – 1,350m (Ananthagiri Hills, Araku Valley)",
    estate: "Smallholder Tribal Cooperatives",
    varietal: "Pure Red Bourbon & SLN 5B",
    process: "Natural Slow Dried on African Raised Beds (28 Days)",
    image: "assets/images/astral_velvet.jpg",
    accentColor: "#E6A15C",
    flavorNotes: ["Mysore Green Cardamom", "Caramelized Black Plum", "Toasted Cashews", "Bourbon Vanilla"],
    description: "Grown entirely organically by indigenous tribal farmers in the red laterite soils of the Eastern Ghats. This coffee has won multiple global accolades in Paris and Tokyo for its silky mouthfeel, cardamom undertones, and clean, caramelized fruit sweetness.",
    recommendedBrew: "AeroPress / Pour-Over / Cold Brew Stasis",
    foodPairings: ["Cardamom Saffron Shrikhand Tart", "Warm Banana Walnut Bread", "Roasted Cashew brittle"],
    caffeineIndex: "Balanced All-Day Harmony",
    radar: {
      intensity: 78,
      acidity: 65,
      sweetness: 90,
      body: 84,
      aroma: 94
    },
    inStock: true,
    isImperialCuration: false
  },
  {
    id: "malabar-monsooned-stasis",
    name: "Malabar Monsooned Stasis",
    subtitle: "16-Week Oceanic Wind Cured (Malabar Coast)",
    category: "heritage-roast",
    badge: "Heritage GI Certified",
    priceINR: 820.00,
    rating: 4.92,
    reviewsCount: 198,
    cuppingScore: 93.8,
    roastLevel: "Dark French Roast (Zero-Astringency)",
    altitude: "Coast-Cured (Origin: Wayanad / Coorg Foothills)",
    estate: "Historical Malabar Open-Air Wind Curers",
    varietal: "Monsooned Arabica AA Super Bold",
    process: "16 Weeks Coastal Southwest Monsoon Wind Exposure",
    image: "assets/images/hero_canister.jpg",
    accentColor: "#FF5500",
    flavorNotes: ["Smoked Malabar Teakwood", "Earthy Nutmeg", "Dark Molasses", "Velvet Crema"],
    description: "A tribute to the colonial maritime era. Green beans are exposed to moisture-laden Arabian Sea monsoon winds in open coastal warehouses. The beans swell, turn golden, and shed all harsh acidity, resulting in the world's most velvet, heavy-bodied crema.",
    recommendedBrew: "9-Bar Espresso / Traditional Moka Pot",
    foodPairings: ["Single-Origin 70% Dark Chocolate", "Tiramisu with Filter Extract", "Rich Pepper Spiced Cheese"],
    caffeineIndex: "Gravitational Heavy Focus",
    radar: {
      intensity: 96,
      acidity: 15,
      sweetness: 82,
      body: 100,
      aroma: 88
    },
    inStock: true,
    isImperialCuration: false
  },
  {
    id: "mysore-imperial-filter-blend",
    name: "Mysore Imperial Royal Filter Blend",
    subtitle: "85% Plantation Arabica PB + 15% Jamnagar Chicory",
    category: "heritage-roast",
    badge: "Royal Court Formula",
    priceINR: 650.00,
    rating: 4.98,
    reviewsCount: 310,
    cuppingScore: 94.0,
    roastLevel: "Full City Dark (Slow Thermal Roasting)",
    altitude: "1,200m – 1,500m (Coorg & Chikmagalur Estate PB)",
    estate: "Mysore Palace Royal Partner Terroirs",
    varietal: "Peaberry (PB) Arabica + Premium Roasted Chicory Root",
    process: "Cryo-Washed & Precision Roasted with Chicory infusion",
    image: "assets/images/obsidian_dark.jpg",
    accentColor: "#D4AF37",
    flavorNotes: ["Dark Chocolate Ganache", "Toasted Chicory Root", "Caramelized Brown Butter", "Malt"],
    description: "The definitive South Indian luxury ritual. Formulated with 85% high-density Peaberry Arabica beans and 15% slow-roasted Jamnagar chicory for unparalleled thickness, golden crema decoction, and deep chocolatey aroma when frothed in a brass Davarah.",
    recommendedBrew: "Traditional South Indian Brass Filter (1st Decoction)",
    foodPairings: ["Crisp Mysore Masala Dosa", "Hot Ghee Rava Kesari", "Cardamom Filter Kulfi"],
    caffeineIndex: "Traditional Energetic Morning Surge",
    radar: {
      intensity: 94,
      acidity: 20,
      sweetness: 85,
      body: 98,
      aroma: 95
    },
    inStock: true,
    isImperialCuration: false
  },
  {
    id: "panama-geisha-imperial-guest",
    name: "Solar Flare: Panama Geisha 2,200m",
    subtitle: "Imperial Guest Micro-Lot (Boquete, Panama)",
    category: "imperial-guest",
    badge: "Global Ultra-Rarity (96.5 Score)",
    priceINR: 2400.00,
    rating: 5.00,
    reviewsCount: 54,
    cuppingScore: 96.5,
    roastLevel: "Ultra-Light Stasis Roast",
    altitude: "2,200m (Volcán Barú Volcanic Slopes)",
    estate: "Private Geisha Highland Parcel",
    varietal: "Green-Tip Geisha 100%",
    process: "Carbonic Anaerobic Maceration (45 Days)",
    image: "assets/images/solar_geisha.jpg",
    accentColor: "#00F0FF",
    flavorNotes: ["Jasmine Blossoms", "White Peach Nectar", "Meyer Lemon Marmalade", "Champagne Yeast"],
    description: "Imported exclusively for our Indian elite patrons in temperature-controlled nitrogen vaults. Produced at 2,200m altitude in Panama, delivering an ethereal tea-like delicacy, explosive floral aromatics, and champagne effervescence.",
    recommendedBrew: "Origami Dripper / Crystal Chemex / Syphon",
    foodPairings: ["Rose & Pistachio Persian Cake", "French White Peach Tart", "Saffron Macarons"],
    caffeineIndex: "Transcendent Lucid Focus",
    radar: {
      intensity: 65,
      acidity: 98,
      sweetness: 96,
      body: 60,
      aroma: 100
    },
    inStock: true,
    isImperialCuration: true
  },
  {
    id: "imperial-brass-davarah-set",
    name: "Imperial Hand-Hammered Brass Davarah Set",
    subtitle: "Heritage Solid Brass Drip Filter + Davarah & Tumbler",
    category: "gear",
    badge: "Handcrafted Luxury Heirloom",
    priceINR: 2800.00,
    rating: 5.00,
    reviewsCount: 88,
    cuppingScore: 99.0,
    roastLevel: "Ritual Extraction Gear",
    altitude: "Artisan Forged in Kumbakonam / Thanjavur",
    estate: "Master Brass Artisans Guild",
    varietal: "Solid Pure Brass with Laser-Etched Wakey Owl Crest",
    process: "Heavy Gauge Hand-Hammered & Polished Mirror Finish",
    image: "assets/images/quantum_extract.jpg",
    accentColor: "#D4AF37",
    flavorNotes: ["Retains Optimal 88°C Thermal Decoction Temperature"],
    description: "An heirloom brewing set hand-crafted by master metal artisans. Includes a heavy-gauge pure brass South Indian drip filter chamber and a traditional Davarah & Tumbler for cooling and frothing your royal morning brew into velvet silk.",
    recommendedBrew: "Essential pairing for Mysore Imperial Royal Filter Blend",
    foodPairings: ["The centerpiece for royal breakfast tables"],
    caffeineIndex: "Brewing Instrument",
    radar: {
      intensity: 100,
      acidity: 0,
      sweetness: 0,
      body: 100,
      aroma: 100
    },
    inStock: true,
    isImperialCuration: true
  }
];

// Grind Options for Indian and Global Brewing
const GRIND_OPTIONS = [
  { id: "whole-bean", label: "Whole Bean (Peak Freshness Sealed)" },
  { id: "south-indian-filter", label: "Fine-Medium — South Indian Brass Filter (Optimal Decoction)" },
  { id: "espresso", label: "Fine — Espresso & Moka Pot (9-Bar Extraction)" },
  { id: "pour-over", label: "Medium-Fine — Pour-Over (V60, Chemex, Kalita)" },
  { id: "french-press", label: "Coarse — French Press & 24h Cold Brew Stasis" },
  { id: "aeropress", label: "Medium — AeroPress Inverted Method" }
];

// Luxury Package Sizes
const BAG_SIZES = [
  { id: "250g", label: "250g Artisanal Tin (18-20 Cups)", multiplier: 1.0 },
  { id: "500g", label: "500g Estate Reserve (36-40 Cups)", multiplier: 1.85, save: "Save 8%" },
  { id: "1kg", label: "1kg Imperial Master Pack (75-80 Cups)", multiplier: 3.4, save: "Save 15%" }
];
